export const workHistory = [
  {
    role: "Front End Engineer",
    company: "Tony Blair Institute for Global Change",
    employment_period: "July 2025 - Present",
    description: [
      "Build responsive, accessible user interfaces using TypeScript, React, and TailwindCSS, with a strong focus on usability and performance.",
      "Own and deliver end-to-end features from the frontend, collaborating with backend services built in Python, Django, and FastAPI as required.",
      "Build internal AI-powered tools leveraging LLMs including Claude, ChatGPT, and Gemini; use Langfuse for prompt monitoring, evaluation, and observability across AI features.",
      "Translate product and design requirements into interactive Figma prototypes and production-ready interfaces.",
      "Design and maintain reusable component libraries and design systems, accelerating development and ensuring consistent UI patterns across applications.",
      "Conduct code reviews to uphold engineering standards, improve code quality, and mentor junior developers.",
      "Implement unit and component tests using React Testing Library and Vitest to ensure reliability and long-term maintainability.",
      "Optimise frontend performance, accessibility (a11y), and cross-browser compatibility to deliver a polished user experience.",
    ],
    skills: [
      "html",
      "css",
      "tailwind",
      "typescript",
      "react",
      "python",
      "django",
      "fastapi",
      "figma",
    ],
  },
  {
    role: "Front End Developer",
    company: "The Big Phone Store",
    employment_period: "April 2024 - July 2025 | 1yr 3 months",
    description: [
      "Built and maintained responsive, production-grade e-commerce interfaces using TypeScript, Vue.js, Nuxt.js, and TailwindCSS, serving live customer traffic.",
      "Translated Figma designs into pixel-perfect, reusable Vue components, ensuring visual and functional consistency across the platform.",
      "Collaborated with backend, design, and product teams to ship end-to-end features within agile sprint cycles.",
      "Improved site performance and Core Web Vitals through code splitting, lazy loading, and image optimisation.",
      "Identified and resolved cross-browser and cross-device compatibility issues to ensure a consistent user experience.",
      "Contributed to the team's component library, promoting reusability and reducing development time for new features.",
      "Participated in code reviews and pair programming to maintain code quality and share knowledge across the team.",
      "Wrote clean, maintainable code following team style guides and Git workflow best practices (branching, PRs, code review).",
    ],
    skills: [
      "html",
      "css",
      "tailwind",
      "javascript",
      "typescript",
      "react",
      "vue",
      "nuxt",
    ],
  },
  {
    role: "Front End Developer Internship",
    company: "The Big Phone Store",
    employment_period: "Feb 2024 - April 2024 | 3 months",
    description: [
      "Developed an e-commerce web application independently using TypeScript, Vue.js, Nuxt.js, and TailwindCSS based on design specifications",
      "Acquired proficiency in Vue.js, Nuxt.js, and TailwindCSS from self-directed learning to deliver production-ready UI within the internship duration",
      "Transformed pixel-perfect designs into responsive, reusable Vue components, ensuring high fidelity to the original design",
      "Integrated the application into the team's frontend development pipeline, gaining practical experience with professional workflows and tools",
    ],
    skills: [
      "html",
      "css",
      "tailwind",
      "javascript",
      "typescript",
      "vue",
      "nuxt",
    ],
  },
];
